---
title: "`r params$params$report_title`"
author:
  - name: "Niels Nielsen"
    affiliation: "CVR: xxx"
date: "`r Sys.Date()`"
output:
  pagedown::html_paged:
    toc: true
    toc_depth: 2
    css: "report_style.css"
    # change to true for a self-contained document, but it'll be a litte slower for Pandoc to render
    self_contained: false
params: 
  params: params
  indicators_df: indicators_df
knit: pagedown::chrome_print
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(root.dir = '/',echo = F,cache=F, warning=F,error=F,message=F)
```

```{r}
library(htmltools)
library(tidyverse)
library(gt)

indicators_df <- params$indicators_df %>%
  select(indicatorID = indicator_ids, 
         indicatorText = indicator_texts,
         indicatorTheme = indicator_themes,
         indicatorUnit = indicator_units) %>%
  mutate(indicatorID = as.character(indicatorID))

df <- params$params %>%  
  stack() %>%
  # rename names generated by stack()
  rename(input_name = ind, input_value = values) %>%
  # drop unanswered questions and irrelevant ui elements
  filter(input_value != "", 
         !is.na(input_value),
         input_value != "TRUE",
         input_value != "FALSE",
         !grepl('select|tabs|sidebar|accordion', input_name)) %>%
  # create indicatorID from input_name (which also contains year)
  separate(input_name,sep = "_", into="indicatorID", remove = FALSE) %>%
  # join with indicator info
  left_join(indicators_df, by = "indicatorID", keep=T) %>%
  as_tibble() %>%
  mutate(input_name = as.character(input_name)) %>%
  select(-indicatorID.y) %>%
  rename(indicatorID = indicatorID.x) %>%
  mutate(
       indicatorTheme = ifelse(
       indicatorID == "initiatives",input_name,indicatorTheme)) %>%
  mutate(indicatorTheme = str_replace(indicatorTheme, "[a-z+_]*", ""))

# get themes
themes_list <- df %>% pull(indicatorTheme) %>% unique()
themes_list <- themes_list[!is.na(themes_list)]

# get intro and facts inputs
intro <- df %>% 
  filter(input_name == "report_intro") %>% 
  pull(input_value)

facts <- df %>% 
  filter(input_name == "report_facts") %>% 
  pull(input_value)

# get intitiatives
initiatives_df <- df %>%
  filter(indicatorID=="initiatives")

df <- df %>%
  select(input_name,Indikator = indicatorText, 
         Enhed = indicatorUnit, 
         Svar = input_value, indicatorTheme) %>%
  drop_na()

# pivot table to have inputs by year as columns
df <- df %>% 
  mutate(year = str_sub(input_name,-4,-1)) %>%
  arrange(desc(year)) %>%
  pivot_wider(names_from = year, 
              values_from = Svar, 
              id_cols = c(Indikator,Enhed, indicatorTheme),
              names_sort = F)

df[is.na(df)] = ""
```


```{r, results="asis", eval=T}

# intro
if (length(intro) > 0) {
  
  cat("\n") 
  cat("#", "Kernefortælling", "\n")
  print(
   tagList(intro)
   )
  cat("\n") 
}

# facts
if (length(facts) > 0) {
  
  cat("\n") 
  cat("##", "Fakta om bedriften", "\n")
  facts <- str_split(facts, "-") %>% 
          map(function(x) x[nchar(x)>1]) %>%
          unlist() %>% 
          str_trim()
        
        print(
          tagList(cat(paste('-', facts), sep = '\n') )
        )
  cat("\n")
}

if ((length(intro) + length(facts)) > 0) {
    cat("\n\n\\pagebreak\n")
}

```


```{r, results="asis", eval=T}

# For each theme..

for(i in themes_list){
  
   theme_initiatives <- initiatives_df %>%
     filter(indicatorTheme == i)
  
  cat("\n")
  cat("#", str_to_title(i), "\n")
  
# TABLES
  print(
   tagList(
    df %>% 
      arrange(Indikator) %>%
      filter(indicatorTheme == i) %>%
      select(-indicatorTheme) %>%
      gt() %>%
      cols_width(Indikator ~ pct(80),everything() ~ pct(20)) %>%
      tab_options(column_labels.font.weight="bold") %>%
      opt_stylize(style = 1, color = "green", 
                  add_row_striping = TRUE)
    )
   )
  cat("\n")

# INITIATIVES
  if (nrow(theme_initiatives) > 0) {

    # current
    current_initiatives <- theme_initiatives %>%
      filter(str_detect(input_name, "curr"))

    if (nrow(current_initiatives) > 0) {
        cat("##", "Nuværende tiltag", "\n")

        inis <- str_split(current_initiatives$input_value, "-") %>%
          map(function(x) x[nchar(x)>1]) %>%
          unlist() %>%
          str_trim()

        print(
          tagList(cat(paste('-', inis), sep = '\n') )
        )
        cat("\n")
      }

      # future
    future_initiatives <- theme_initiatives %>%
        filter(str_detect(input_name, "fut"))

    if (nrow(future_initiatives) > 0) {
        cat("##", "Fremtidige tiltag", "\n")

        inis <- str_split(future_initiatives$input_value, "-") %>%
          map(function(x) x[nchar(x)>1]) %>%
        unlist()

        print(
          tagList(cat(paste('-', inis), sep = '\n') )
        )
        cat("\n")
    }

  }
      cat("\n\n\\pagebreak\n")

}
```
